title: Ian C. McCormack
org: "PhD Student @ Carnegie Mellon"
suborg: "Institute for Software Research"
description: >- # this means to ignore newlines until "baseurl:"
domain: "icmccorm.me"
url: "https://icmccorm.me" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
social_tag: icmccorm
phone: "+1-651-239-0832"
email: icmccorm@andrew.cmu.edu
orcid_id: "0000-0001-6349-3402"
# Build settings

source: ./
sass:
    sass_dir: assets/css/_sass
    style: compressed
favicon:
  path: assets/img

collections:
  - publications
  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
